function federalelections2016S2 = importFedElecData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  FEDERALELECTIONS2016S2 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  FEDERALELECTIONS2016S2 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  FEDERALELECTIONS2016S2 = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  federalelections2016S2 = importfile("/Users/Bdflamholz/Desktop/DAI Final Round/federalelections2016.xlsx", "Table 2. Electoral &  Pop Vote", [5, 62]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Aug-2019 18:40:01

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [5, 62];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["STATE", "ELECTORALVOTE", "ELECTORALVOTE1", "POPULARVOTE", "POPULARVOTE1", "POPULARVOTE2", "POPULARVOTE3"];
opts.SelectedVariableNames = ["STATE", "ELECTORALVOTE", "ELECTORALVOTE1", "POPULARVOTE", "POPULARVOTE1", "POPULARVOTE2", "POPULARVOTE3"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 1, "EmptyFieldRule", "auto");

% Import the data
federalelections2016S2 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    federalelections2016S2 = [federalelections2016S2; tb]; %#ok<AGROW>
end

end